/**
 * Obtient la description complète d'une devise
 * @param {string} code - Code de la devise (ex: "USD", "EUR", "AED")
 * @returns {string} - Description complète de la devise
 */
export const getCurrencyDescription = (code) => {
  const descriptions = {
    // Fiat - Principales
    "USD": "US Dollar",
    "EUR": "Euro",
    "GBP": "British Pound",
    "JPY": "Japanese Yen",
    "CHF": "Swiss Franc",
    "CAD": "Canadian Dollar",
    "AUD": "Australian Dollar",
    "NZD": "New Zealand Dollar",
    "CNY": "Chinese Yuan",
    "CNH": "Chinese Yuan Offshore",
    "HKD": "Hong Kong Dollar",
    "SGD": "Singapore Dollar",
    "KRW": "South Korean Won",
    "INR": "Indian Rupee",
    "BRL": "Brazilian Real",
    "MXN": "Mexican Peso",
    "ZAR": "South African Rand",
    "RUB": "Russian Ruble",
    "TRY": "Turkish Lira",
    "SEK": "Swedish Krona",
    "NOK": "Norwegian Krone",
    "DKK": "Danish Krone",
    "PLN": "Polish Zloty",
    "CZK": "Czech Koruna",
    "HUF": "Hungarian Forint",
    "RON": "Romanian Leu",
    
    // Moyen-Orient
    "AED": "Emirati Dirham",
    "SAR": "Saudi Arabian Riyal",
    "QAR": "Qatari Riyal",
    "KWD": "Kuwaiti Dinar",
    "BHD": "Bahraini Dinar",
    "OMR": "Omani Rial",
    "JOD": "Jordanian Dinar",
    "ILS": "Israeli Shekel",
    "IQD": "Iraqi Dinar",
    "SYP": "Syrian Pound",
    "LBP": "Lebanese Pound",
    "YER": "Yemeni Rial",
    
    // Asie
    "THB": "Thai Baht",
    "MYR": "Malaysian Ringgit",
    "IDR": "Indonesian Rupiah",
    "PHP": "Philippine Peso",
    "VND": "Vietnamese Dong",
    "PKR": "Pakistani Rupee",
    "BDT": "Bangladeshi Taka",
    "LKR": "Sri Lankan Rupee",
    "NPR": "Nepalese Rupee",
    "AFN": "Afghan Afghani",
    "MMK": "Burmese Kyat",
    "KHR": "Cambodian Riel",
    "LAK": "Lao Kip",
    "TWD": "Taiwan Dollar",
    "MOP": "Macanese Pataca",
    
    // Amérique Latine & Caraïbes
    "ARS": "Argentine Peso",
    "CLP": "Chilean Peso",
    "COP": "Colombian Peso",
    "PEN": "Sol",
    "SOL": "Sol",
    "VES": "Venezuelan Bolivar",
    "UYU": "Uruguayan Peso",
    "PYG": "Paraguayan Guarani",
    "BOB": "Bolivian Boliviano",
    "CRC": "Costa Rican Colon",
    "GTQ": "Guatemalan Quetzal",
    "HNL": "Honduran Lempira",
    "NIO": "Nicaraguan Cordoba",
    "PAB": "Panamanian Balboa",
    "DOP": "Dominican Peso",
    "HTG": "Haitian Gourde",
    "JMD": "Jamaican Dollar",
    "TTD": "Trinidad and Tobago Dollar",
    "BBD": "Barbadian Dollar",
    "BSD": "Bahamian Dollar",
    "BZD": "Belizean Dollar",
    "SVC": "Salvadoran Colon",
    "CUP": "Cuban Peso",
    
    // Afrique
    "EGP": "Egyptian Pound",
    "MAD": "Moroccan Dirham",
    "TND": "Tunisian Dinar",
    "DZD": "Algerian Dinar",
    "LYD": "Libyan Dinar",
    "NGN": "Nigerian Naira",
    "GHS": "Ghanaian Cedi",
    "KES": "Kenyan Shilling",
    "UGX": "Ugandan Shilling",
    "TZS": "Tanzanian Shilling",
    "ETB": "Ethiopian Birr",
    "AOA": "Angolan Kwanza",
    "MZN": "Mozambican Metical",
    "ZMW": "Zambian Kwacha",
    "BWP": "Botswana Pula",
    "MUR": "Mauritian Rupee",
    "SDD": "Sudanese Dinar",
    "SDG": "Sudanese Pound",
    "XOF": "West African CFA Franc",
    "XAF": "Central African CFA Franc",
    
    // Europe de l'Est & autres
    "ALL": "Albanian Lek",
    "BGN": "Bulgarian Lev",
    "RSD": "Serbian Dinar",
    "BAM": "Bosnia-Herzegovina Convertible Mark",
    "MKD": "Macedonian Denar",
    "UAH": "Ukrainian Hryvnia",
    "BYN": "Belarusian Ruble",
    "BYR": "Belarusian Ruble",
    "MDL": "Moldovan Leu",
    "GEL": "Georgian Lari",
    "AMD": "Armenian Dram",
    "AZN": "Azerbaijani Manat",
    "KZT": "Kazakhstani Tenge",
    "UZS": "Uzbekistani Som",
    "TJS": "Tajikistani Somoni",
    "KGS": "Kyrgyzstani Som",
    "TMT": "Turkmenistan Manat",
    "MNT": "Mongolian Tugrik",
    "ISK": "Icelandic Krona",
    
    // Océanie
    "FJD": "Fijian Dollar",
    "PGK": "Papua New Guinean Kina",
    "SBD": "Solomon Islander Dollar",
    "TOP": "Tongan Pa'anga",
    "WST": "Samoan Tala",
    "VUV": "Vanuatu Vatu",
    "XPF": "CFP Franc",
    
    // Stablecoins
    "RLUSD": "Ripple USD Stablecoin",
    "USDT": "Tether USD Stablecoin",
    "USDC": "USD Coin Stablecoin",
    "BUSD": "Binance USD Stablecoin",
    "DAI": "DAI Stablecoin",
    "TUSD": "TrueUSD Stablecoin",
    "USDP": "Pax Dollar Stablecoin",
    "GUSD": "Gemini Dollar Stablecoin",
    
    // Cryptomonnaies
    "XRP": "XRP Ledger Native Token",
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "BNB": "Binance Coin",
    "ADA": "Cardano",
    "DOGE": "Dogecoin",
    "MATIC": "Polygon",
    "DOT": "Polkadot",
    "LINK": "Chainlink",
    "AVAX": "Avalanche",
    "UNI": "Uniswap",
    "ATOM": "Cosmos",
    "XLM": "Stellar Lumens",
    "ALGO": "Algorand",
    "VET": "VeChain",
    "ICP": "Internet Computer",
    "FIL": "Filecoin",
    "NEAR": "Near Protocol",
    "APT": "Aptos",
    "ARB": "Arbitrum",
    "OP": "Optimism",
    "RLUSD": "Xcannes Coin",
    "SHIB": "Shiba Inu",
    "TRX": "Tron",
    "LTC": "Litecoin",
    "BCH": "Bitcoin Cash",
    "XMR": "Monero",
    "ETC": "Ethereum Classic",
    "XTZ": "Tezos",
    "EOS": "EOS",
    "AAVE": "Aave",
    "MKR": "Maker",
    "COMP": "Compound",
    "SNX": "Synthetix",
    "CRV": "Curve DAO",
    "SUSHI": "SushiSwap",
    "YFI": "Yearn Finance",
    "BAT": "Basic Attention Token",
    "ZRX": "0x Protocol",
    "ENJ": "Enjin Coin",
    "CHZ": "Chiliz",
    "THETA": "Theta Network",
    "FTM": "Fantom",
    "HBAR": "Hedera",
    "EGLD": "MultiversX (Elrond)",
    "FLR": "Flare",
    "XDC": "XDC Network",
    "KAVA": "Kava",
    "ZIL": "Zilliqa",
    "QTUM": "Qtum",
    "WAVES": "Waves",
    "ICX": "ICON",
    "ONT": "Ontology",
    "ZEC": "Zcash",
    "DASH": "Dash",
    "DCR": "Decred",
  };
  
  return descriptions[code] || "Exchange Rate Account";
};
