/**
 * useWalletModalProps
 * -------------------
 * Centralise la construction des props partagées entre les versions desktop
 * (inline / aside) et mobile (portalisées) des modales du wallet.
 *
 * L'objectif est d'éliminer la duplication : chaque jeu de props est calculé
 * une seule fois, puis consommé par WalletDesktopModals et WalletMobileModals.
 */

import { useMemo } from "react";

export function useWalletModalProps({
  // --- identité du wallet ---
  wallet,
  isConnected,
  isWalletActivated,
  hasOnChainRlusd,
  walletLabel,
  walletHasCustomLabel,
  renderWalletMeta,
  signTransaction,
  connect,

  // --- actions / state machines ---
  activeAction,
  setActiveAction,

  // --- Send ---
  qrSizingVariant,
  selectableTokens,
  augmentedTokens,
  selectedSendToken,
  sendFxInfo,
  setSendAssetKey,
  sendAmount,
  setSendAmount,
  sendPaymentRequest,
  setSendPaymentRequest,
  moonpaySellRequest,
  selectLabelByAssetKey,
  selectLabelRightByAssetKey,
  selectIconByAssetKey,
  selectLabelMobileByAssetKey,
  savedAddresses,
  sendDestination,
  setSendDestination,
  sendDestinationLabel,
  setSendDestinationLabel,
  setQrScannerOpen,
  handlePaymentRequestScan,
  handleSendSubmit,
  sendProcessing,
  hasPayreq,
  savePayreq,
  removePayreq,

  // --- Receive ---
  receiveTab,
  setReceiveTab,
  handleCopyAddress,
  requestAmount,
  setRequestAmount,
  requestCurrency,
  setRequestCurrency,
  requestMemo,
  setRequestMemo,
  rlusdPerUnitRates,
  rlusdPerUnitSources,

  // --- Swap / Convert ---
  swapDefaultView,
  swapLockedView,
  swapCurrencyOptionsForModal,
  convertBaseCurrency,
  setConvertBaseCurrency,
  convertQuoteCurrency,
  setConvertQuoteCurrency,
  convertAmount,
  setConvertAmount,
  convertPreview,
  convertProcessing,
  handleInstallRequiredTrustline,
  handleActivateCurrencyLine,
  effectiveRefreshCurrencyLines,
  effectiveCurrencyLinesLoading,
  effectiveCurrencyLinesError,
  effectiveCurrencyLinesSummary,
  effectiveCurrencyLines,
  currencyLineCode,
  setCurrencyLineCode,
  currencyLineAllocatedRlusd,
  setCurrencyLineAllocatedRlusd,
  handleUpsertCurrencyLine,
  handleDemoConvert,

  // --- Cash ---
  cashModalTab,
  setCashModalTab,
  cashBuyPrefill,
  setCashBuyPrefill,

  // --- Activation ---
  showActivationModal,
  setShowActivationModal,
  handleActivationSendFromWallet,
  handleActivationRequestFromThirdParty,
  handleActivationBuyViaMoonpay,

  // --- Activation Request ---
  showActivationRequestModal,
  setShowActivationRequestModal,

  // --- Info ---
  walletInfoOpen,
  setWalletInfoOpen,

  // --- Statements ---
  displayTokensWithCurrencyLines,
  backendWalletAddress,
  usdRates,
  preferredCurrency,
  showGlobalStatement,
  setShowGlobalStatement,
  showCurrencyStatement,
  setShowCurrencyStatement,
  selectedStatementToken,
  setSelectedStatementToken,
  statementBalance,

  // --- QR ---
  qrScannerOpen,
  handleAddressScan,

  // --- Toast ---
  toast,
  // --- Reset ---
  resetSendForm,
  resetReceiveForm,
  resetSwapForm,
  resetCashForm,
}) {
  // --- Send modal props ---
  const sendModalProps = useMemo(
    () => ({
      currentWalletAddress:
        typeof wallet === "string" ? wallet : wallet?.address || "",
      qrSizingVariant,
      renderWalletMeta,
      augmentedTokens: moonpaySellRequest ? augmentedTokens : selectableTokens,
      selectedSendToken,
      sendFxInfo,
      setSendAssetKey,
      sendAmount,
      setSendAmount,
      sendPaymentRequest,
      moonpaySellRequest,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      savedAddresses,
      sendDestination,
      setSendDestination,
      sendDestinationLabel,
      setSendDestinationLabel,
      setQrScannerOpen,
      handlePaymentRequestScan,
      handleSendSubmit,
      sendProcessing,
      enableSaveAddress: true,
      resetSendForm,
      toast,
    }),
    [
      wallet,
      qrSizingVariant,
      renderWalletMeta,
      augmentedTokens,
      selectableTokens,
      moonpaySellRequest,
      selectedSendToken,
      sendFxInfo,
      setSendAssetKey,
      sendAmount,
      setSendAmount,
      sendPaymentRequest,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      savedAddresses,
      sendDestination,
      setSendDestination,
      sendDestinationLabel,
      setSendDestinationLabel,
      setQrScannerOpen,
      handlePaymentRequestScan,
      handleSendSubmit,
      sendProcessing,
      resetSendForm,
      toast,
    ],
  );

  // --- Payreq modal props ---
  const payreqModalProps = useMemo(
    () => ({
      renderWalletMeta,
      augmentedTokens: selectableTokens,
      selectedSendToken,
      sendFxInfo,
      setSendAssetKey,
      setSendAmount,
      sendPaymentRequest,
      sendDestination,
      sendAmount,
      sendProcessing,
      handleSendSubmit,
      savedAddresses,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      enableSaveAddress: true,
      savePayreq,
      removePayreq,
    }),
    [
      renderWalletMeta,
      selectableTokens,
      selectedSendToken,
      sendFxInfo,
      setSendAssetKey,
      setSendAmount,
      sendPaymentRequest,
      sendDestination,
      sendAmount,
      sendProcessing,
      handleSendSubmit,
      savedAddresses,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      savePayreq,
      removePayreq,
    ],
  );

  // --- Receive modal props ---
  const receiveModalProps = useMemo(
    () => ({
      dashboardVariant: "full",
      receiveTab,
      setReceiveTab,
      renderWalletMeta,
      wallet,
      handleCopyAddress,
      requestAmount,
      setRequestAmount,
      requestCurrency,
      setRequestCurrency,
      selectLabelByCurrency: selectLabelByAssetKey,
      selectLabelRightByCurrency: selectLabelRightByAssetKey,
      selectIconByCurrency: selectIconByAssetKey,
      selectLabelMobileByCurrency: selectLabelMobileByAssetKey,
      augmentedTokens: selectableTokens,
      requestMemo,
      setRequestMemo,
      rlusdPerUnitRates,
      rlusdPerUnitSources,
      walletLabel,
      resetReceiveForm,
    }),
    [
      receiveTab,
      setReceiveTab,
      renderWalletMeta,
      wallet,
      handleCopyAddress,
      requestAmount,
      setRequestAmount,
      requestCurrency,
      setRequestCurrency,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      selectableTokens,
      requestMemo,
      setRequestMemo,
      rlusdPerUnitRates,
      rlusdPerUnitSources,
      walletLabel,
      resetReceiveForm,
    ],
  );

  // --- Swap modal props ---
  const swapModalProps = useMemo(
    () => ({
      renderWalletMeta,
      defaultView: swapDefaultView,
      lockedView: swapLockedView,
      dashboardVariant: "full",
      isConnected,
      isWalletActivated,
      walletAddress: wallet,
      onConnectWallet: connect,
      hasOnChainRlusd,
      onInstallTrustline: handleInstallRequiredTrustline,
      onActivateCurrencyLine: handleActivateCurrencyLine,
      refreshCurrencyLines: effectiveRefreshCurrencyLines,
      currencyLinesLoading: effectiveCurrencyLinesLoading,
      currencyLinesError: effectiveCurrencyLinesError,
      currencyLinesSummary: effectiveCurrencyLinesSummary,
      currencyLines: effectiveCurrencyLines,
      swapCurrencyOptions: swapCurrencyOptionsForModal,
      convertBaseCurrency,
      setConvertBaseCurrency,
      convertQuoteCurrency,
      setConvertQuoteCurrency,
      convertAmount,
      setConvertAmount,
      convertPreview,
      selectLabelByCurrency: selectLabelByAssetKey,
      selectLabelRightByCurrency: selectLabelRightByAssetKey,
      selectIconByCurrency: selectIconByAssetKey,
      selectLabelMobileByCurrency: selectLabelMobileByAssetKey,
      currencyLineCode,
      setCurrencyLineCode,
      currencyLineAllocatedRlusd,
      setCurrencyLineAllocatedRlusd,
      handleUpsertCurrencyLine,
      handleDemoConvert,
      convertProcessing,
      rlusdPerUnitRates,
      resetSwapForm,
    }),
    [
      renderWalletMeta,
      swapDefaultView,
      swapLockedView,
      isConnected,
      isWalletActivated,
      wallet,
      connect,
      hasOnChainRlusd,
      handleInstallRequiredTrustline,
      handleActivateCurrencyLine,
      effectiveRefreshCurrencyLines,
      effectiveCurrencyLinesLoading,
      effectiveCurrencyLinesError,
      effectiveCurrencyLinesSummary,
      effectiveCurrencyLines,
      swapCurrencyOptionsForModal,
      convertBaseCurrency,
      setConvertBaseCurrency,
      convertQuoteCurrency,
      setConvertQuoteCurrency,
      convertAmount,
      setConvertAmount,
      convertPreview,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      currencyLineCode,
      setCurrencyLineCode,
      currencyLineAllocatedRlusd,
      setCurrencyLineAllocatedRlusd,
      handleUpsertCurrencyLine,
      handleDemoConvert,
      convertProcessing,
      rlusdPerUnitRates,
      resetSwapForm,
    ],
  );

  // --- Cash modal props ---
  const cashModalProps = useMemo(
    () => ({
      cashModalTab,
      setCashModalTab,
      renderWalletMeta,
      walletLabel,
      preferredFiatCurrency: preferredCurrency,
      rlusdPerUnitRates,
      selectLabelByCurrency: selectLabelByAssetKey,
      selectLabelRightByCurrency: selectLabelRightByAssetKey,
      selectIconByCurrency: selectIconByAssetKey,
      selectLabelMobileByCurrency: selectLabelMobileByAssetKey,
      walletAddress: wallet || "",
      buyPrefill: cashBuyPrefill,
      resetCashForm,
    }),
    [
      cashModalTab,
      setCashModalTab,
      renderWalletMeta,
      walletLabel,
      rlusdPerUnitRates,
      selectLabelByAssetKey,
      selectLabelRightByAssetKey,
      selectIconByAssetKey,
      selectLabelMobileByAssetKey,
      wallet,
      cashBuyPrefill,
      resetCashForm,
      preferredCurrency,
    ],
  );

  // --- Activation modal props ---
  const activationModalProps = useMemo(
    () => ({
      onSendFromWallet: handleActivationSendFromWallet,
      onRequestFromThirdParty: handleActivationRequestFromThirdParty,
      onBuyViaMoonpay: handleActivationBuyViaMoonpay,
    }),
    [
      handleActivationSendFromWallet,
      handleActivationRequestFromThirdParty,
      handleActivationBuyViaMoonpay,
    ],
  );

  // --- Activation Request modal props ---
  const activationRequestModalProps = useMemo(
    () => ({
      walletAddress: wallet,
    }),
    [
      wallet,
    ],
  );

  // --- Info modal props ---
  const infoModalProps = useMemo(
    () => ({}),
    [],
  );

  // --- Statement shared props ---
  const statementSharedProps = useMemo(
    () => ({
      augmentedTokens: displayTokensWithCurrencyLines || augmentedTokens,
      backendWalletAddress,
      wallet,
      walletDisplayLabel: walletHasCustomLabel ? walletLabel : "",
      isWalletActivated,
      hasRlusdTrustline: hasOnChainRlusd,
      rlusdBalance: effectiveCurrencyLinesSummary?.rlusdOnChain ?? null,
      isFullPageView: true,
      statementVariant: "full",
      usdRates,
      preferredCurrency,
      rlusdPerUnitRates,
      showGlobalStatement,
      setShowGlobalStatement,
      showCurrencyStatement,
      setShowCurrencyStatement,
      selectedStatementToken,
      setSelectedStatementToken,
      statementBalance,
      toast,
    }),
    [
      displayTokensWithCurrencyLines,
      augmentedTokens,
      backendWalletAddress,
      wallet,
      walletHasCustomLabel,
      walletLabel,
      isWalletActivated,
      hasOnChainRlusd,
      effectiveCurrencyLinesSummary,
      usdRates,
      preferredCurrency,
      rlusdPerUnitRates,
      showGlobalStatement,
      setShowGlobalStatement,
      showCurrencyStatement,
      setShowCurrencyStatement,
      selectedStatementToken,
      setSelectedStatementToken,
      statementBalance,
      toast,
    ],
  );

  // --- RLUSD Setup modal props --- (removed: setup handled by WalletSetupDropdown)

  return {
    sendModalProps,
    payreqModalProps,
    receiveModalProps,
    swapModalProps,
    cashModalProps,
    activationModalProps,
    activationRequestModalProps,
    infoModalProps,
    statementSharedProps,

    // open / close handlers needed by both desktop & mobile
    activeAction,
    setActiveAction,
    hasPayreq,
    showActivationModal,
    setShowActivationModal,
    showActivationRequestModal,
    setShowActivationRequestModal,
    walletInfoOpen,
    setWalletInfoOpen,
    setSendPaymentRequest,
    setCashBuyPrefill,
    resetSendForm,
    resetReceiveForm,
    resetSwapForm,
    resetCashForm,
    qrScannerOpen,
    setQrScannerOpen: setQrScannerOpen,
    handleAddressScan,

    // Cash modal uses different availableTokens in desktop vs mobile
    selectableTokens,
    augmentedTokens,
  };
}
